### ISSUE TITLE
Make it clearer that `timeout` configuration affects mocked as well as non-mocked requests

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1046]
In [`cy.request()`](https://on.cypress.io/request) and also main [configuration doc](https://on.cypress.io/configuration#Timeouts), make it clearer that `responseTimeout` applies to mocked as well as non-mocked requests.

**Comment by jennifer-shehane** [comment]
I'm closing this. This issue is a bit strange in itself. cy.request() doesn't allow mocking in any sense, so it doesn't make sense to even refer to a 'mocked' request. Maybe this should be clearer somehow? But...I'm not totally sure how to address the original users confusion.

**Comment by mitar** [comment]
I think the main confusion is that `cy.request` does not mention that `responseTimeout` is in effect. See [timeouts](https://docs.cypress.io/api/commands/request.html#Timeouts) section. One would assume that setting `timeout` would work, and that `responseTimeout` is just a default, but this is not what I observed.

**Comment by mitar** [comment]
What is unclear about this issue? The issue is that `responseTimeout` controls timeouts of XHR requests, so even if you do not use `cy.request`, a timeout magically happens. I think this is what you meant by "mocked" vs "non-mocked":

* mocked: `cy.request`
* non-mocked: XHR request

**Comment by jennifer-shehane** [comment]
>So maybe a reference to cy.request() was made by mistake. 

Yeah, I think there was some confusion when initially opening the documentation issue. I was under the belief that you were using `cy.request()` as part of your code - which cannot be mocked, but if you were trying to change the `responseTimeout` that is passed through to `cy.wait()` when waiting for a defined `cy.route()` then the documentation can clarify that applies to mocked and non-mocked in that case. 

Is this accurate?

**Comment by mitar** [comment]
No. What I have is a node module which internally uses XHR. It does long-polling to stream data, by opening and keeping connection open long. My problem is that this connection has been during testing closed prematurely, why otherwise it has not been. The culprit was that Cypress modifies XHR and adds timeout to it. I would say this should not be done at all, but that is a discussion for some other issue, like https://github.com/cypress-io/cypress/issues/2592. This issue is about documenting that timeout configuration also influences those XHR requests which are not part of test suite at all.

**Comment by mitar** [comment]
I also made a new comment here: https://github.com/cypress-io/cypress/issues/2592#issuecomment-471764542
