### ISSUE TITLE
best way to interact with the redux store from cypress tests?

### ISSUE THREAD

**Issue by mcmunder** [cypress-io/cypress-documentation#1115]
Could anyone point me to a resource that describes how to best interact with the redux store (expect the store to have a certain shape, dispatch actions...) from a cypress test? The documentation states that with cypress you can "Expose data stores (like in Redux) so you can programmatically alter the state of your application directly from your test code." but I can't find any information about how to actually do that 😉

I submit the issue as a feature request because this information could be added to the documentation?

Thanks for creating cypress! It's awesome!!

**Comment by bahmutov** [comment]
@mcmunder I moved your question to this repo, because this is a better place for it. Quick answer: look at https://www.cypress.io/blog/2017/11/28/testing-vue-web-application-with-vuex-data-store-and-rest-backend/ - but I will add your question and an answer to https://docs.cypress.io/faq/questions/using-cypress-faq.html as well

**Comment by mcmunder** [comment]
thanks a lot!
