### ISSUE TITLE
Organize media queries file 

### ISSUE THREAD

**Issue by anjanab96** [cypress-io/cypress-documentation#1170]

**Comment by jennifer-shehane** [comment]
The lefthand nav is messed up again within the example blogs since this PR https://github.com/cypress-io/cypress-documentation/pull/1160

<img width="759" alt="screen shot 2018-11-27 at 12 40 32 am" src="https://user-images.githubusercontent.com/1271364/49033310-2f64c600-f1dd-11e8-95e8-8f6ea3610b2d.png">
