### ISSUE TITLE
Reporter Options have not correct CMD script for Windows

### ISSUE THREAD

**Issue by Saibamen** [cypress-io/cypress-documentation#1201]
From: https://docs.cypress.io/guides/guides/reporters.html#Reporter-Options

When you run Cypress on Windows and you already added `"cypress": "cypress"` in `scripts` section in your `package.json` file you can't start reporter in Cypress with command from official Cypress documentation:
`cypress run --reporter junit --reporter-options "mochaFile=results/my-test-output.xml,toConsole=true"`

Correct way to do this is:
`npm run cypress run -- --reporter junit --reporter-options "mochaFile=results/my-test-output.xml,toConsole=true"`

Please note **--** after run command

BTW: "Improve this doc" link is broken

**Comment by jennifer-shehane** [comment]
Hey @Saibamen, update this documentation to specify `npm run cypress` would assume that everyone has written their npm scripts as `cypress: cypress`. Since we can't verify that this is the case (it's not the case in any of our own projects for sure), we will not statically suggest running `npm run cypress`. 

We may want to update the documentation in some pivotal command line docs to remind users that in order to pass [arguments to an npm script](https://docs.npmjs.com/cli/run-script) that it requires `-- <args>..` since we've seen several users get stuck on this.
