### ISSUE TITLE
Document how to debug Cypress itself including clearing App Data within Debugging doc

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1378]
## I'm submitting a...

```
[ ] Bug report 
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Update https://docs.cypress.io/guides/guides/debugging.html#Using-debugger to have section about debugging Cypress Install? Cypress Commands? Cypress Run? - launching the Test Runner? to describe how to clear app data. 

Also, what the heck does 'Debugging the Browser Driver' mean. This should be renamed to something much more useful. 

**Conclusion:** I think we should have *Advanced* section that describes debugging problems with Cypress itself. 

- [x] List all the places we have for support questions. 
- [x] Explain how to get DEBUG logs
- [ ] Explain how to run other versions of Chromium @flotwig 	
- [x] Explain how to log all events run within the test runner in your console
- [x] Explain how to clear App Data. 

**How to clear App Data**
 
- Open Cypress via `cypress open`
- Go to `File` -> `View App Data`
- This should take you to the directory in your file system where your App Data is stored. If you cannot open Cypress, try searching your file system for a directory named `cy`. The content should look something like this:
	
<img width="438" alt="screen shot 2019-02-01 at 11 48 38 am" src="https://user-images.githubusercontent.com/1271364/52104130-60b3a500-2617-11e9-8102-641462c704a6.png">

- Delete everything in here
- Close Cypress and open it up again

**Comment by Nikh27091** [comment]
Unable to install Cypress on Mac

<img width="564" alt="cypress_Issue" src="https://user-images.githubusercontent.com/78801730/107368868-117a9780-6aaf-11eb-999d-8a1dd90a992d.png">

Getting below error


Opening Cypress...
Cypress could not verify that this server is running:

  > http://localhost:3000

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
