### ISSUE TITLE
Clarify the definition of "users" in paid plans

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress-documentation#1500]
## I'm submitting a...

<pre><code>
[x] Bug report 
[ ] Content update
[ ] Process update (build, deployment, ... )
</code></pre>

## Type of bug / changes

All of the paid plans list a maximum number of users. (https://www.cypress.io/pricing/)
I am confused what a user is. I am hoping that the documentation and/or FAQ could be improved to clarify this.

Things a user might be:

* Anyone on your project who might want to run `cypress open` or `cypress run`
* Anyone who needs to log in to the dashboard service
* Anyone who needs to view the dashboard service (can this be done anonymously?)
* Anyone who might need to submit runs to the dashboard service (including CI?)
* None of the above? Something else?

**Comment by jennifer-shehane** [comment]
The answer is:

>Anyone who needs to log in to the dashboard service 

- this includes the "Runs" tab of the Test Runner also

**Comment by fr0** [comment]
Does this mean I need to have an account for my CI to publish data to the dashboard service? Or does it not need  to "log in" to publish the data?

**Comment by jennifer-shehane** [comment]
The project needs to be set up on the Dashboard in order to record data to the Dashboard, so at least one person would have to log in initially to set up the project. 

After this, anyone with the record key and access to the actual git project would be able to record data to the Dashboard - no need to log in. 

They will be unable to review the recorded data from the Dashboard, however, without a log in and invitation as a 'user' to a private project. 

Public projects are just that - they require a log in to the Dashboard, but you do not have to be an invited user of the project to view the data.

**Comment by fr0** [comment]
That makes sense - thanks for the clarification.

**Comment by zootechdrum** [comment]
Does this still need to be worked on?
