### ISSUE TITLE
How to translate questions

### ISSUE THREAD

**Issue by yardenfi** [cypress-io/cypress-documentation#1595]
I have some questions about translating the docs:
1. Is there a way for me to determine the direction of the text? my language requires right to left text. I'v managed to achieve that by wraping every section in the markdown with 
```html 
<div dir="rtl">some text from right to left..</dir>
```
 but it won't change the style or work for the page title and such, and it isn't so pretty either..
Maybe a "dir" field on the metadata of each page shouls be added..

2. I'v added translation for the links in the site to my language, but clicking them redirects you to the english version. how should I fix this? 

	to see an example of this: 
	* clone [https://github.com/yardenfi/cypress-documentation] (https://github.com/yardenfi/cypress-documentation)
	* run `npm run buld & npm start`
	* open `http://localhost:2222/`

	* switch to hebrew("עברית")
![cypress english](https://user-images.githubusercontent.com/25435999/56460385-94969f00-63aa-11e9-9a8d-0caa7077971a.PNG)

	* click on any of the links..
![cypress hebrew](https://user-images.githubusercontent.com/25435999/56460384-94969f00-63aa-11e9-847a-339a9e236e2b.PNG)

**Comment by jennifer-shehane** [comment]
I've been working on translation support lately. I've update it so that you can add a meta data direction and the page should display rtl. This will be a bit weird with some of the English mixed in since it rtl the English as well. 

https://github.com/cypress-io/cypress-documentation/pull/1716

Example of meta data

```
---
title: למה לבחור בסייפרס?
dir: rtl
---
```

<img width="1665" alt="Screen Shot 2019-05-24 at 3 58 52 PM" src="https://user-images.githubusercontent.com/1271364/58317964-e2d10f00-7e3c-11e9-8196-9cdf5d0c6935.png">

There's likely more optimizations we can make for this - comment in this issue, as it is keeping track of language optimizations. https://github.com/cypress-io/cypress-documentation/issues/1686
