### ISSUE TITLE
Mention CYPRESS_PROJECT_ID in the FAQ about project id

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#175]
in https://docs.cypress.io/faq/questions/using-cypress-faq.html#What-is-the-projectId-for need to say that if you do not want to commit project id, set it as environment variable

**Comment by richdouglasevans** [comment]
So I'm waiting for my train to arrive and I thought _"Mmm, is there a low-hanging fruit issue I can scope out?"_ Browsing around I spy this one and it looks both fruity and low-hanging. Bingo!

But... I bingo'd too soon. (Oh, the shame!) I _can_ do exactly as Gleb says in the ticket and add a wee mention in the FAQ. But... don't I also want to update the bit in the _Dashboard Service_ section that's almost word for word the same content?

<img width="1661" alt="screen shot 2018-08-24 at 18 18 22" src="https://user-images.githubusercontent.com/1855109/44598420-e3b01400-a7ca-11e8-8110-65f638e8c6e4.png">

Is this duplication intentional? Does the work to close this issue extend to adding the mention in both places? Or does the work extend to addressing the duplication and adding the mention once?

Well, wouldn't you know it... the train is late 😆

**Comment by jennifer-shehane** [comment]
This duplication may not be necessary - since we don't want the content to go stale in one area. 

The piece of info that is missing and should likely be in the Dashboard service area - is the mention of using `CYPRESS_PROJECT_ID` as an environment variable from your CI provider if needed.

**Comment by richdouglasevans** [comment]
The change that was requested is now merged so can this ticket be `Closed`?

> Well, wouldn't you know it... the train is late 😆

My train finally arrived... in the form of a bus replacement 😆
