### ISSUE TITLE
How can I get the element selector value?

### ISSUE THREAD

**Issue by dizhar** [cypress-io/cypress-documentation#2432]
## Type of explain

How can I get the element selector value?

For example:
Lets say I setup the element selector like so:

public function getSubmitButton(){
let element = cy.get("[data-test='buttonSubmit']");
console.log(element)
}

The console.log(element) outputs a unique chaninerId value. However I want to get the selector value.

How can I get the selector value? I want to get the string "data-test='buttonSubmit'".

Perhaps I can use the unique chainerId value to get the element selector value?

please advise?

**Comment by jennifer-shehane** [comment]
Issues in this GitHub repo are reserved for potential bugs or requests for documentation changes. This issue will be closed since it appears to be neither a bug nor a docs request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
