### ISSUE TITLE
when will cypress take failure screenshot?

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress-documentation#2622]
## I'm submitting a...

```
[this ] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

"Additionally, Cypress will automatically capture screenshots when a failure happens during cypress open. Screenshots on failure are not automatically taken during cypress open."

This looks wrong at https://docs.cypress.io/guides/guides/screenshots-and-videos.html#Screenshots

**Comment by jennifer-shehane** [comment]
This is wrong - I merged this in yesterday, let me fix it.

**Comment by jennifer-shehane** [comment]
Fixed in https://github.com/cypress-io/cypress-documentation/commit/eb1420bd503237fa583145f0db338510a39a2d36

Should have said:

"Additionally, Cypress will automatically capture screenshots when a failure happens during cypress run. Screenshots on failure are not automatically taken during cypress open."
