### ISSUE TITLE
Ability to collapse navigation and TOC sidebars to have middle column wider.

### ISSUE THREAD

**Issue by MNF** [cypress-io/cypress-documentation#2827]
## I'm submitting a...

```
layout change request
```

## Type of bug / changes

I am using iPad to read documentation ( e.g. https://docs.cypress.io/examples/examples/recipes.html ) and the main middle content column is quite narrow. Often I don’t care about both left and right sidebars and wish to hide them to have bigger real estate for main column.

Can sidebars be collapsible to be very narrow to just show expand buttons?
Alternatively can content column have toggled ‘full-screen’ button to show it on full real-estate and ‘show sidebars’ button to return to the current 3-columns view?
(Attn @jennifer-shehane)

**Comment by jennifer-shehane** [comment]
The sidebar does collapse at a certain point, so likely these media queries need to be adjusted to account for ipad sizes or ipad useragent itself. 

https://github.com/cypress-io/cypress-documentation/blob/develop/themes/cypress/source/css/_media_queries.scss

![](http://g.recordit.co/ELHcphXnFS.gif)

**Comment by flozender** [comment]
Hi, can I help with this? As far as I understand, we need to modify the threshold at which the alternative mobile view kicks in to accommodate iPad resolutions. Please let me know if I can start working on it. Thanks.

**Comment by michael-freidgeim-webjet** [comment]
Sorry, if my request wasn’t clear.
On the original resolution ( more than 1000) the page is divided into 3 almost equal width columns ( not exactly, the middle column is slightly wider). When user reading the page,  they concerned about content and do not need navigation at most of the time. 
I suggest to give to user control to see content on the full real estate of the page or only on the middle column. 
Responsive design of the page is good, but you make decision for the user instead of providing flexible control by the user.

**Comment by TaniaMalhotra** [comment]
Hii! @jennifer-shehane I am a newbie to open source! I would be really like to work on this issue. I believe this can be resolved by altering the size of the middle column to adapt to the iPad dimensions.

**Comment by michael-freidgeim-webjet** [comment]
I just  noticed an example Page https://code.visualstudio.com/Docs/languages/javascript#_jsdoc-support, where sidebars do exist, but do not take so much real estate, and the middle column takes about 3/4 of the total width.It will be good if your layout will be similar.

**Comment by jennifer-shehane** [comment]
Yes, anyone is welcome to open a PR.
