### ISSUE TITLE
Equivalent method to moveToElement of Actions class in Selenium?

### ISSUE THREAD

**Issue by Pallabee94** [cypress-io/cypress-documentation#2880]
When I move the mouse on an element it is visible, otherwise it's not. Need to perform click on it after it is visible. What method to be used to move to the element so that it becomes visible?

**Comment by jennifer-shehane** [comment]
Issues in our Docs repo are reserved for changes required in our docs. This issue will be closed since it appears to not be related to documentation changes.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
