### ISSUE TITLE
Link to tutorial videos +++ within doc articles.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#289]
Our tutorial videos are great! They cover a lot of concepts that are in our guides and even usages with our commands. I'd love to see links directly from the guides/api to the tutorial. 

Honestly, I would even encourage just embedding the video directly in some places. Is there a great section of a video tutorial that explains `.as()`? Add it in the `.as()` doc, within the examples - *can we embed the video and have it jump to the exact spot in the video? Even better!*

**Comment by avanslaars** [comment]
We can link to a specific time... The UI in Vimeo for this is a little weird... you pause the video, click "share" and then you have to select the URL in the "link" option. Click on the URL then gives you the option to start at a specific time:

<img width="545" alt="screenshot 2017-12-01 10 14 41" src="https://user-images.githubusercontent.com/1271181/33488987-8441e41a-d680-11e7-9c23-921ead8f5291.png">

Leaving this here because this is not very obvious

**Comment by brian-mann** [comment]
Yes definitely. For those harder to understand concepts we should link to the exact video and timestamp as well.
