### ISSUE TITLE
Key Differences

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#29]
@brian-mann commented on [Wed Jul 05 2017](https://github.com/cypress-io/cypress-monorepo/issues/276)

---

@bahmutov commented on [Fri Jul 07 2017](https://github.com/cypress-io/cypress-monorepo/issues/276#issuecomment-313771563)

Post the deployed link as answer to https://twitter.com/taminderb/status/883395281886208004

**Comment by brian-mann** [comment]
This is in a PR in the monorepo for reference. It needs to be moved into this repo.

https://github.com/cypress-io/cypress-monorepo/pull/280

**Comment by richdouglasevans** [comment]
I believe this issue can be closed because:

* there's a [Key Differences](https://docs.cypress.io/guides/overview/key-differences.html#) section in the docs.
* Brian added the above section a month after his comment about the PR in the monorepo (`e715eaaf707e2477d3fdb5091324fd2603e2aecc`)

Burn it with fire? 🔥 😄
