### ISSUE TITLE
Add dependency information for installing Cypress on RedHat Linux OS

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress-documentation#2963]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Per the issue at https://github.com/cypress-io/cypress/issues/660, there are additional dependencies required to install Cypress on a RedHat Linux machine. Commenters confirmed they have been able to install on up to 7.3. 

We should add a section to the installation page or and FAQ entry noting this and recommending they use one of our Docker images which has the Cypress dependencies already installed.

Related: https://github.com/cypress-io/cypress-documentation/issues/206 (some comments here refer to additional dependencies)

**Comment by jennifer-shehane** [comment]
Yah, I added a new section to the install for Linux deps recently actually, because it was hidden in the CI page before. https://docs.cypress.io/guides/getting-started/installing-cypress.html#Linux 

Content for this can be found here https://github.com/cypress-io/cypress-documentation/blob/develop/source/_partial/linux_dependencies.md#L14:L14

cc @flotwig

**Comment by CypressCecelia** [comment]
Sorry for not seeing this -- the user said they didn't see anything in the install docs but they may have been looking specifically for RedHat instead of Linux. Thanks, I'll close out.
