### ISSUE TITLE
Clarify test config section

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#3200]
Seems from comments in https://github.com/cypress-io/cypress/pull/5346#issuecomment-701376447 a user can be confused by which config parameters _filter_ tests vs modify the config. We should make the section clearer https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Test-Configuration

**Comment by paleite** [comment]
Ran into the same issue as that user.
It seems the interface can be confusing because, on one hand, it queries ("is it running in the correct browser?"), on the other hand, it performs an action ("set this environment variable to this value").

Furthermore, the type is called `Cypress.TestConfigOverrides`, but setting `{browser: "chrome"}` will not override which browser should be used for the test.

Having super clear interfaces is one of the big selling-points which got me into Cypress in the first place, and I'd love to see this happening with this interface as well, for the greater good of Cypress' community.

One possible way to go forward is to break the object down further or introducing a new parameter where you explicitly define which parts are overrides and which parts are preconditions. To illustrate:

```
  it(
    "testname",
    {
      overrides: {
        env: {
          myproperty: "myvalue",
        },
      },
      precondition: {
        browser: "!chrome",
      },
    },
    () => {
      /* test */
    }
  );
```
