### ISSUE TITLE
Request  to add docs regarding how to set up Cypress as a service

### ISSUE THREAD

**Issue by conversayShawn** [cypress-io/cypress-documentation#4118]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

I couldn't find any documentation relating to tests against services that weren't publicly accessible.

**Comment by eahrend** [comment]
For us, there are two use cases where this becomes necessary:

1. During our CD pipelines, we would deploy a new version of a web app on a staging environment which is cut off from the public internet. We would like our pipeline to execute tests and come back with a response as to whether or not the tests are passing or failing so we can stop the pipeline or continue to deploy to the next environment.
2. We have microservices that exist behind an API layer that we'd want to test independent of that API layer, but since these are HTTP services that cannot be reached by the public internet, how can we get cypress to run those tests?
