### ISSUE TITLE
had a hard time finding discord link 

### ISSUE THREAD

**Issue by petitkriket** [cypress-io/cypress-documentation#4309]
### Subject

reach community chat

### Description

Hello !

## issue description

Had a hard time finding Cypress discord channel, found a "gitter" channel on the docs, which was itself hard to find (link is small).

Since Discord is widely adopted by devs, would it make sense to additionally display discord link , or even replace the gitter link ?

I have a bunch of examples of siblings
- [Storybook Community page](https://storybook.js.org/community) and footer element, 
- [Strapi community page](https://strapi.io/community) and footer element
- [Nuxt footer element](https://nuxtjs.org/)
- [Chakra UI Vue navbar](https://vue.chakra-ui.com/).

## proposed solution

- add a discord link to the [support page itself](https://www.cypress.io/support/) or further replace chat link and logo by discord's which is more recognizable
- add a discord icon and link the footer elements

![Screenshot 2022-01-13 at 10 54 27](https://user-images.githubusercontent.com/1753019/149309556-28d04ec1-25ac-4620-9c91-ca43940d65fc.png)

**Comment by MikeMcC399** [comment]
@petitkriket 

It looks like this issue is resolved.

- https://www.cypress.io/support/ contains information and links to Discord.

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/06f07fa2-951a-4559-bd45-c65723b61b9f)

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/1583f2e7-4257-4c93-bff0-533da422f6a3)

- https://docs.cypress.io/ links to Discord

![Snag_2bb3f33](https://github.com/cypress-io/cypress-documentation/assets/66998419/33afc223-1c53-49d9-8436-ff260d655b76)

![Snag_2bb4cdf](https://github.com/cypress-io/cypress-documentation/assets/66998419/040748f3-16fb-4c76-bd50-8ee78f9efc96)

- https://github.com/cypress-io/cypress-documentation/blob/main/README.md links to Discord

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/544b0bd6-9aec-429d-9199-a9d8cd7524b9)
