### ISSUE TITLE
Explain Cypress GUI 'reloading' when 'baseUrl' not set

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#447]
Adding a baseUrl to your cypress.json should fix the 'flashing' of initial load -> refresh -> run tests. Cypress essentially does not know before opening where you are planning to visit (unless specified in cypress.json), so it initially opens on localhost + a random port, then switches to the localhost + port you specified in your visit.

Cypress internally switches to the domain that you use in your cy.visit() so that your application’s code will run under the current domain at all times.

We had a lot of CORS related issues before when we did not set the main window to the same url as the application under test. Previously we implemented an endless amount of hacks and internal translations to figure out the domain you were supposed to be on without actually being on the domain. This caused code to behave different and caused subtle issues.

The entire proxy layer was written to handle https certificates, continue to inject (even on https pages), and know when to automatically bypass injection so you can open other tabs while testing in Cypress. This also allows us to unlock the ability to do things like whitelisting or blacklisting specific 3rd party domains, or even be able to stub not just XHR’s but any kind of HTTP request.

**Comment by brian-mann** [comment]
I wouldn't add paragraphs 3 and 4. I remember writing them, but they're too much information.

I would add that this is how Cypress warns you when the server isn't running too (in the GUI).

It also allows you to omit the baseUrl from things like `cy.visit` and `cy.request` since it will assume that's what you're trying to visit.

All wins, no downside.

We should maybe even add a warning in `cypress run` that tells you to set it.

**Comment by jennifer-shehane** [comment]
Did we want this in the 'Best Practices' doc?
