### ISSUE TITLE
Hmm, our users seem not to notice Algolia search box

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#471]
@bahmutov commented on [Tue Mar 20 2018](https://github.com/cypress-io/cypress.io/issues/225)

I watched a power user learning Cypress and using it to write E2E tests and he has NOT used our search box - that was very interesting and unexpected. We should call attention to the search box, maybe with color or placeholder text to let users know they can find everything quickly there

Video for anyone interested

https://www.youtube.com/watch?v=w8liCoPsDIU

---

@jennifer-shehane commented on [Tue Mar 20 2018](https://github.com/cypress-io/cypress.io/issues/225#issuecomment-374653779)

Isn't this an issue in [cypress-documentation](https://github.com/cypress-io/cypress-documentation)?

---

@bahmutov commented on [Tue Mar 20 2018](https://github.com/cypress-io/cypress.io/issues/225#issuecomment-374655719)

Yeah true! Will move 

Sent from my iPhone

> On Mar 20, 2018, at 12:02, Jennifer Shehane <notifications@github.com> wrote:
> 
> Isn't this an issue in cypress-documentation?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

**Comment by richdouglasevans** [comment]
Huh, I don't use it either 😳I'll start.

On a related note is takes *8* presses of the `TAB` key to focus the search box. (In Chrome: the tab index seems all out of whack on Safari.) There's explicit `:focus` styling in the current theme to _remove_ the focus styling with the result that the user can't visually see which element has the focus.

Adding explicit focus styling so that it "pops" when focused might help. So too might adding a wee tooltip that eagerly pops up... but that might be too intrusive if not toggled off with a cookie.

I'll have a play around.
