### ISSUE TITLE
Move 'userland extensions' doc to a section w/in Examples

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#49]
I had difficulty finding the Typescript definitions the other day. I expected them to be in the examples area, but it's in this weird doc that's kind of out of place. Should be moved within examples.

**Comment by brian-mann** [comment]
This was fixed by https://github.com/cypress-io/cypress-documentation/pull/51 but you never explicitly said: "fixes #49" so Github never associated this issue to the PR.

If you add that language anywhere in a comment, the PR title, or the PR body it'll link and automatically close when the PR is merged.

**Comment by brian-mann** [comment]
Fixed by #51
