### ISSUE TITLE
Custom Query example is misleading

### ISSUE THREAD

**Issue by Eugene-Kuzmenko** [cypress-io/cypress-documentation#5041]
### Subject

api

### Description

https://docs.cypress.io/api/cypress-api/custom-queries

Documentation for Custom Queries lists as example a fragment from internal implementation of `focused` query. The documentation omits that `Command` and it's `addQuery` is different form the one used might use. In [the file it most likely uses as an example](https://github.com/cypress-io/cypress/blob/release/12.2.0/packages/driver/src/cy/commands/querying/focused.ts) `Command` received through a function argument

Most misleading is that user can alter timeout with `this.set('timeout', options.timeout)`, even though, based on the typescript definition, "timeout" key isn't allowed. And if you still use it, it does not alter timeout time, even though documentation specifically explains what that line does

**Comment by BlueWinds** [comment]
> In [the file it most likely uses as an example](https://github.com/cypress-io/cypress/blob/release/12.2.0/packages/driver/src/cy/commands/querying/focused.ts) `Command` received through a function argument

You're right, I'll fix that; it should be `Cypress.Commands.addQuery()`.

Receiving the `Commands` object is related to Cypress' internal implementation of how we add commands while bootstrapping the `Cypress` and `cy` objects; it's not needed when adding custom queries in user code. I'll update the example, thanks for the report.

I'll also remove the references to `$dom`, so that the example can be run copy-pasted exactly as is. :+1: 

> Most misleading is that user can alter timeout with `this.set('timeout', options.timeout)`, even though, based on the typescript definition, "timeout" key isn't allowed. And if you still use it, it does not alter timeout time, even though documentation specifically explains what that line does

We may have a bug with our typescript types; I'd encourage you to open an issue in the Cypress repo directly with a reproducible example, but this code 100% does work.

![image](https://user-images.githubusercontent.com/3003404/222225707-4d9f2890-f7e1-49f7-9961-b4ca3691f66e.png)

It's also what we used when implementing all of Cypress' builtin queries.

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/querying/focused.ts#L7
https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/traversals.ts#L100
https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/window.ts#L92
and many others.

Is it possible you used an arrow function, rather than `function()` when defining the query function?

**Comment by BlueWinds** [comment]
Opened https://github.com/cypress-io/cypress-documentation/pull/5097 to address some of the points brought up, thanks for letting me know!

**Comment by devfservant** [comment]
I was about to reopen an issue; my code looked like:

```typescript
// support/index.ts
Cypress.Commands.addQuery('getById', function getByIdFn(id: string, options?: Partial<Cypress.Loggable & Cypress.Timeoutable>) {
  this.set('timeout', options?.timeout);
  const getFn = cy.now('get', `[data-testid="${id}"]`) as GetFn;
  return () => getFn();
});
```

and the timeout was not taken into account:

```typescript
// integration/some-test.cy.ts
cy.getById('does-not-exist', { timeout: 10000 });
```

![image](https://github.com/cypress-io/cypress-documentation/assets/43757707/a0ac1f8c-2865-4a6b-90b0-4065d71eb3b2)

Then I simply inverted the `this.set(...)` and the `cy.now(...)` lines and it passed:

```typescript
const getFn = cy.now('get', `[data-testid="${id}"]`) as GetFn;
this.set('timeout', options?.timeout);  
```

![image](https://github.com/cypress-io/cypress-documentation/assets/43757707/062f3767-3c1f-4b4f-96da-834b1c03f3c3)

Super weird. The documentation on Custom Queries should be improved
