### ISSUE TITLE
>12.17.1 Regression

### ISSUE THREAD

**Issue by stychu** [cypress-io/cypress-documentation#5409]
### Description

Currently running on `"cypress": "12.5.1"` so I wanted to update to the latest version `12.17.3` but as soon as I try to run my tests on 12.17.3 my tests fail. They freeze at the login stage (session + origin) with no errors at all. Test just enter the login page and stops, after timeout test fails but without any error at all.

### URL of Issue(s)

.

### Browser

Chrome v115, Electron v106

### Device

- [ ] PC
- [X] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

Tests fails on `12.17.3` `12.17.2` but they do work fine on `12.17.1`.

After running with DEBUG I see 
```
Timed out after waiting `60000ms` for your remote page to load.\n' + '\n' + 'Your page did not fire its `load` event within `60000ms`.\n' + '\n' + 'You can try increasing the `pageLoadTimeout`..
```
 Which is weird because this ALWAYS happens in like 4th test where all previous tests are able successfully go through login.
 
 This is what I get when running with `cypress run --headed`
<img width="514" alt="Screenshot 2023-08-03 at 16 45 15" src="https://github.com/cypress-io/cypress-documentation/assets/9383657/6aba94ce-f208-44ae-aa7b-5fca12ee4679">

**Comment by MikeMcC399** [comment]
@stychu 

This repository is for issues with the Cypress documentation on https://docs.cypress.io/ not with Cypress itself.

Perhaps one of the moderators will be kind enough to move your issue to https://github.com/cypress-io/cypress? Or you yourself could open a new issue there. From a practical point of view you would need to supply a reproducible example in order to get help there.

An alternative is to contact the Cypress technical community on Discord where users assist each other

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)
(click on button)

**Comment by stychu** [comment]
@MikeMcC399 Awww My bad.. I didn't even notice im sumbmitting to wrong repo 😶‍🌫️
