### ISSUE TITLE
Is there a Cypress version that supports Chrome 66 browser？

### ISSUE THREAD

**Issue by Whiskeyi** [cypress-io/cypress-documentation#5887]
### Description

I want to do automated testing on Chrome 66 based pages, but I encountered an error during actual execution.The version of Cypress I am using is 10.11.0.Can I change a version of Cypress to solve this problem?

### URL of Issue(s)

https://docs.cypress.io/guides/guides/launching-browsers#Chrome-Browsers

### Env

Linux_x64_Chrome 66

The document states that it is supported.
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/92f1a025-680e-4a7e-a254-2369341ca85b">

**Comment by Whiskeyi** [comment]
Error call stack：
<img width="1126" alt="image" src="https://github.com/user-attachments/assets/9d8e702e-6225-4aa9-a1ef-e6f68668b7ac">

**Comment by MikeMcC399** [comment]
- Chrome 66 was [released](https://chromereleases.googleblog.com/2018/04/stable-channel-update-for-desktop.html) on April 17, 2018. This is quite a long time ago.

- In the Changelog for [Cypress 10.8.0](https://docs.cypress.io/guides/references/changelog#10-8-0) there is an entry which mentions this version of Chrome. So you might like to try Cypress `10.8.0`:

  - Fixed a regression introduced in Cypress [10.0.0](https://docs.cypress.io/guides/references/changelog#10-0-0) where Cypress was incompatible with Chrome v64 - v70. Fixes [#23509](https://github.com/cypress-io/cypress/issues/23509).

- There is an open issue concerning conflicting information in the documentation about whether Chrome 64 or 80 is the minimum version. See https://github.com/cypress-io/cypress-documentation/issues/5446. Despite what it says, you should probably consider Chrome 80 as the lowest version which works with current Cypress versions `13.x`.

- The nearest Cypress Docker image would be `cypress/browsers:chrome67` however that would be problematic to use, since it is based on Debian 8 (end-of-life June 2020) and Node.js `v8.10.0` (end-of-life December 2019). Cypress currently requires minimum Debian 11 and Node.js `18.x`.

**Comment by Whiskeyi** [comment]
@MikeMcC399 Thanks a lot for your reply!
After I replaced it with version 10.8.0, the error still persists, and the error is not as described in issue https://github.com/cypress-io/cypress/issues/23509

<img width="821" alt="image" src="https://github.com/user-attachments/assets/21bb85ad-2dd7-469d-9600-4129ba90439f">

Chrome 66 was indeed released a long time ago, but our automated testing has this scenario to test lower version browsers

Based on your description, I will try Chrome 67 again later.

I hope that the minimum compatible version of the browser can be clearly stated in the documentation in the future.

**Comment by MikeMcC399** [comment]
@Whiskeyi 

It will be difficult to get support for your testing because Node.js `14.x` is no longer supported. It entered [end-of-life](https://github.com/nodejs/release#release-schedule) in April 2023.

> I hope that the minimum compatible version of the browser can be clearly stated in the documentation in the future.

See https://github.com/cypress-io/cypress-documentation/issues/5446 for discussion about official statements. Chrome < 80 is expected to be deprecated.

**Comment by MikeMcC399** [comment]
@Whiskeyi 

There was some confusion about older Browser support which is now clarified in the documentation.

The statement is that you can test against Chrome 64 and later with the latest version of Cypress 13.x. To use `cypress open` you need a minimum of Chrome 80.

Since issues in this repository are only about documentation, this issue should be closed now.

In any case the problem with `Fetch.enable` may be a problem with Chrome, not a problem with Cypress. If you feel this is a bug in Cypress you should open a new issue in https://github.com/cypress-io/cypress/issues

**Comment by Whiskeyi** [comment]
ok, thank you!

**Comment by Whiskeyi** [comment]
@MikeMcC399 The issue with the error is due to our use of experimental features(`experimentalSessionAndOrigin` configuration option ), which are not supported in lower versions of browsers. After disabling this option, the issue has been resolved.
In the 12.0.0 changelog document, I see that this configuration item has been removed and automatically enabled。
<img width="799" alt="image" src="https://github.com/user-attachments/assets/9f0a6e4f-c641-423c-8480-1a5b8ac964a1">
