### ISSUE TITLE
Include the versions commands changed / were added / updated, etc

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#716]
Now that we have had several breaking changes and upgrades, we need to probably start versioning the API commands so people can see when they were added, etc

**Comment by richdouglasevans** [comment]
Is this the kind of thing you're looking for?

<img width="688" alt="since" src="https://user-images.githubusercontent.com/1855109/44954037-d82caf00-ae94-11e8-935b-b3178fbafde9.png">

That's a hyperlink there: clicking it takes you to the changelog for the version.

This is controlled via the `sinceVersion` value in the front matter of the Markdown source.

```
---
title: task
sinceVersion: 3.1.0
---

Execute code in...
```

If this is what you're looking for then I'll submit a PR. If not, then... steer me.

**Comment by richdouglasevans** [comment]
Another part of this issue is to identify the version that each command was released in. I'd suggest "flooring" most of 'em at `1.0.0` 'cos I dunno that anyone will care to know that a command was released in `0.2.whatever`.

I have gone through the changelog; find below all of the commands plus their versions.

> :open_mouth: It's just `task`. Er, I might well be wrong and have missed something :smile:

I have not yet done the same investigation for other API such as assertions, plugins, events, etc. 

> Yeah, I've assumed that the scope of this issue extends to not just the API commands but also the plugin API, events, CLI, etc. Steer me if such are not in scope.

| Command  | Since Version |
| ------------- | ------------- |
| `and` | `1.0.0` |
| `as` | `1.0.0` |
| `blur` | `1.0.0` |
| `check` | `1.0.0` |
| `children` | `1.0.0` |
| `clear` | `1.0.0` |
| `clearCookie` | `1.0.0` |
| `clearCookies` | `1.0.0` |
| `clearLocalStorage` | `1.0.0` |
| `click` | `1.0.0` |
| `clock` | `1.0.0` |
| `closest` | `1.0.0` |
| `contains` | `1.0.0` |
| `dblclick` | `1.0.0` |
| `debug` | `1.0.0` |
| `document` | `1.0.0` |
| `each` | `1.0.0` |
| `end` | `1.0.0` |
| `eq` | `1.0.0` |
| `exec` | `1.0.0` |
| `filter` | `1.0.0` |
| `find` | `1.0.0` |
| `first` | `1.0.0` |
| `fixture` | `1.0.0` |
| `focus` | `1.0.0` |
| `focused` | `1.0.0` |
| `get` | `1.0.0` |
| `getCookie` | `1.0.0` |
| `getCookies` | `1.0.0` |
| `go` | `1.0.0` |
| `hash` | `1.0.0` |
| `hover` | `1.0.0` |
| `invoke` | `1.0.0` |
| `its` | `1.0.0` |
| `last` | `1.0.0` |
| `location` | `1.0.0` |
| `log` | `1.0.0` |
| `next` | `1.0.0` |
| `nextAll` | `1.0.0` |
| `nextUntil` | `1.0.0` |
| `not` | `1.0.0` |
| `parent` | `1.0.0` |
| `parents` | `1.0.0` |
| `parentsUntil` | `1.0.0` |
| `pause` | `1.0.0` |
| `prev` | `1.0.0` |
| `prevAll` | `1.0.0` |
| `prevUntil` | `1.0.0` |
| `readFile` | `1.0.0` |
| `reload` | `1.0.0` |
| `request` | `1.0.0` |
| `root` | `1.0.0` |
| `route` | `1.0.0` |
| `screenshot` | `1.0.0` |
| `scrollIntoView` | `1.0.0` |
| `scrollTo` | `1.0.0` |
| `select` | `1.0.0` |
| `server` | `1.0.0` |
| `setCookie` | `1.0.0` |
| `should` | `1.0.0` |
| `siblings` | `1.0.0` |
| `spread` | `1.0.0` |
| `spy` | `1.0.0` |
| `stub` | `1.0.0` |
| `submit` | `1.0.0` |
| `task` | `3.0.0` |
| `then` | `1.0.0` |
| `tick` | `1.0.0` |
| `title` | `1.0.0` |
| `trigger` | `1.0.0` |
| `type` | `1.0.0` |
| `uncheck` | `1.0.0` |
| `url` | `1.0.0` |
| `viewport` | `1.0.0` |
| `visit` | `1.0.0` |
| `wait` | `1.0.0` |
| `window` | `1.0.0` |
| `within` | `1.0.0` |
| `wrap` | `1.0.0` |
| `writeFile` | `1.0.0` |

| Cypress API  | Since Version |
| ------------- | ------------- |
| `Commands` | `1.0.0` |
| `Cookies` | `1.0.0` |
| `Screenshot` | `3.0.0` |
| `SelectorPlayground` | `1.0.0` |
| `Server` | `1.0.0` |
| `arch` | `1.1.3` |
| `browser` | `3.0.2` |
| `config` | `1.0.0` |
| `env` | `1.0.0` |
| `log` | `1.0.0` |
| `platform` | `1.1.3` |
| `spec` | `3.0.2` |
| `version` | `1.1.3` |

**Comment by richdouglasevans** [comment]
Finally, there's also the change to the process of documenting API.

Documenters must know to add a `sinceVersion` to the front matter and reviewers must know to check for it.

I'll add such instruction to the `CONTRIBUTING.md` file.

**Comment by jennifer-shehane** [comment]
Decide whether toggling versioned docs may be easier than this ^ @lilaconlee is going to look into this work. Thanks @richdouglasevans !!

**Comment by lilaconlee** [comment]
Okie doke, did some [digging around other documentation](https://gist.github.com/lilaconlee/cea2e5ac3f3f334afb2acc88686ab4bf) and the idea that sounds the best to me is a select in the header that allows you to access the full docs site for each major version.

![screen shot 2018-09-17 at 4 00 26 pm](https://user-images.githubusercontent.com/7514489/45650181-1a5c1000-ba93-11e8-8eee-6b6e93c578d3.png)

The latest version could live at the same urls as always with versioned URLs like `https://docs.cypress.io/2.1.0/guides/overview/why-cypress.html#In-a-Nutshell` or  `https://docs.cypress.io/2.x/guides/overview/why-cypress.html#In-a-Nutshell`. 

Considerations:
* Hosting: From the deploy script, seems like docs are just living in s3. Not exactly sure what s3 hijinks need to be done, but that’s where the work is.
* Tracking/editing old docs: How do we want to delineate versions of docs? How would we edit and re-deploy old docs? I’m thinking when deploying breaking changes we’d tag the existing content and deploy to wherever legacy docs live, then merge in breaking content and publish as the latest version.
* Search: Not 100% on how search is set up or how that would get mucked up by adding older versions.
* What if we build new docs though: Seems like if we’re thinking about rebuilding docs in the next six months or so, we should just develop a standard message format for breaking API changes or implement the original design on this issue, then bake versioning into the new docs

**Comment by lilaconlee** [comment]
@jennifer-shehane @brian-mann and I talked about this, decided we should show history or details for significant changes between versions and not have several versions of docs. Something like node's history would be good: 

![Screen Shot 2018-09-25 at 12.37.10 PM.png](https://images.zenhubusercontent.com/5b96832e96c0801aed18b88c/2fe22763-7f3c-4349-9ad3-d4751942491a)

**Comment by lilaconlee** [comment]
Did a quick spike, but bulk of the work would be adding this to relevant pages. There's also no check that the tag input is actually a MD table, which might be worthwhile.

Default:
<img width="669" alt="screen shot 2018-10-10 at 3 53 11 pm" src="https://user-images.githubusercontent.com/7514489/46765498-c82e9900-cca4-11e8-86bb-593f8dfbdc65.png">
Open:
<img width="690" alt="screen shot 2018-10-10 at 3 53 20 pm" src="https://user-images.githubusercontent.com/7514489/46765499-c8c72f80-cca4-11e8-8a71-3b725a1d9f15.png">
Code:
```
{% history %}
| 3.1.1 | Added `flag` option and appending with `a+`
| 1.0.0 | Introduced
{% endhistory %}
```
