### ISSUE TITLE
Double dash formatting could confuse users

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-documentation#923]
In an info box, the theme seems to combine two dashes into one, turning `--record` into `-record` which can confuse people.

![screen shot 2018-09-10 at 4 06 32 pm](https://user-images.githubusercontent.com/334337/45329163-e7a29c80-b513-11e8-909d-b8ba7d523fdf.png)

**Comment by richdouglasevans** [comment]
If you add `smartypants: false` to the `_config.yml` file then the issue goes away.

```yaml
marked:
  autolink: false
  smartypants: false
```

![bingo](https://user-images.githubusercontent.com/1855109/45345961-c4253380-b59f-11e8-8a13-2cb62d9897c8.png)

However, that's kinda nuclear: it turns off [SmartyPants](https://daringfireball.net/projects/smartypants/) processing _for the entire site._

> _"[SmartyPants] easily translates plain ASCII punctuation characters into “smart” typographic punctuation HTML entities."_
>
> SmartyPants can perform the following transformations:
>
> * Straight quotes ( " and ' ) into “curly” quote HTML entities
> * Backticks-style quotes (``like this'') into “curly” quote HTML entities
> * Dashes (“--” and “---”) into en- and em-dash entities
> * Three consecutive dots (“...”) into an ellipsis entity

I dunno that there's all that many occurrences of the above markdown that is transformed by SmartyPants; I know that I've been explicitly adding `&mdash;` and `&hellips;` to the source code on the odd occasion that I needed them. (I didn't know that SmartyPants was even a thing.)

There's the tactical approach where SmartyPants is turned off which is appealing because it can be done right now and stops users possibly getting confused. Downside is that the sweet typography goes away... which I'm not sure is all that big a deal when compared to removing a source of possible confusion.

Then there's the strategic approach which is to keep SmartyPants turned on but sort out why it's FoJangledZor in the `note` blocks.

Thoughts?

> _Random Guy On The Internet_ votes for the tactical approach to be merged in but for the ticket to remain open.

😄

**Comment by jennifer-shehane** [comment]
From smartypants docs, it shouldn't format anything in code blocks like this example is.

> SmartyPants does not modify characters within <pre>, <code>, <kbd>, or <script> tag blocks.

Honestly, I'm not seeing a lot of benefit from SmartyPants. It's very much not worth having actual code flags rendering incorrectly. I would turn off SmartyPants

Still, yes, there is likely something not being handled correctly in our note blocks that this just puts a bandaid over.

**Comment by amirrustam** [comment]
when I turn off smartypants, I get an `Request to: network-requests#Don’t-Stub-Responses failed.`

**Comment by richdouglasevans** [comment]
Yeah; with SmartyPants turned off completely it means that the anchors aren't processed. Anchors with `'` in 'em such as `Don't Stub Responses` get encoded into `Don-39-t-Stub-Responses` and well, yeah.

I've submitted a PR that _tactically_ addresses this. The PR doesn't close this issue 'cos I'll look to solve the problem at source.

**Comment by richdouglasevans** [comment]
I've submitted a PR to the `marked` project to solve this issue at source.

https://github.com/markedjs/marked/pull/1335

I dunno if the PR will be accepted, but if it is:

* and there is a subsequent release
* then we can explicitly bump the version of `marked` in the cypress docs so that Hexo picks it up
* and Amir and I can resume partying like it is 1999.

OMG the _tension_ on this _important issue itt iz srs bsnss_ 😰😝

**Comment by richdouglasevans** [comment]
> I've submitted a PR to the marked project to solve this issue at source.

That fix has been released. I'll test it locally to see if it fixes this issue and, if so, then I'll create a PR to address it and revert the earlier tactical fix... but later this week, possibly next weekend 'cos I'm proper busy at the mo'.

https://github.com/markedjs/marked/releases/tag/v0.5.1

**Comment by amirrustam** [comment]
Thanks @richdouglasevans
