### ISSUE TITLE
Make Documentation Step by step

### ISSUE THREAD

**Issue by emalstm** [cypress-io/cypress-documentation#970]
Hi,
I'm having issues following your Documentation. The prerequisites for using Cypress are not listed, and I who am a software tester without previous knowledge of Javascript cannot follow due to too many things being explicit.

Furthermore I am forced to use Windows and cmder, and the instruction video fails me in the first step - I cannot open cypress in the specified way. The installing-cypress.md also fails me - there are simply no instructions that are comprehensible to me. I suspect there to be some steps missing for Windows and/or for Windows with cmder.  

I have googled how to open cypress in cmder and get nb relevant hits.

**Comment by richdouglasevans** [comment]
I hear you.

Yes, the [_Installing Cypress_ page](https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-Requirements) does assume that the reader is up to speed with Node and `npm` or `yarn`.

I don't think that's necessarily a bad thing, but it is _a_ thing. I'm not sure that the Cypress docs should start from scratch with instructions about how to install Node and `npm`/`yarn` but maybe there's a blog post in the offing that I -- or someone else in the community -- could write.

Mmm, how to proceed? 🤔

I have some time this evening so I'll install Cypress from scratch on my Windows box using cmder as my shell. I have a Windows box for gaming only so it doesn't have any programming-related stuff on it so it'll be fresh. I'll let you know what issues I encounter tomorrow morning, hopefully that'll help.

**Comment by tschernobyl** [comment]
Thanks a lot!
I think that stating the prerequisites should be sufficient, even nicer with links to resources on their installation. 

I've been working on this today aswell and although I do get new error messages (good!) I can't launch the application or run a suite from an existing project. Devs in my organization haven't had any issues, so it's probable that I lack some vital information about prerequisites that they find are obvious.

**Comment by richdouglasevans** [comment]
Hiya,

Here are the steps that I took to get Cypress running on a Windows laptop from scratch.

## Install Cmder with Git

I installed the version of Cmder that comes with Git built-in.

https://github.com/cmderdev/cmder/releases/download/v1.3.6/cmder.zip

I installed it into `C:/opt/cmder/`

## Install Node

Cypress is a Node (JavaScript) program so next I installed Node.

https://nodejs.org/en/download/

Here's a direct link to the version of Node that I installed. It's an MSI so double-click it and accept all the prompts.

https://nodejs.org/dist/v8.12.0/node-v8.12.0-x64.msi

I've installed to `C:/opt/node/`

This'll give us access to some important programs:

* `npm` :: to install modules such as Cypress
* `npx` :: to more easily run executable modules such as Cypress

## Create A Project

Let's create a project so that we can use Cypress to test a website.

Open Cmder and change to the root of your C drive.

```shell
cd C:/
```

Create a directory called `bilibin` there.

```shell
mkdir bilibin
```

Change into that directory.

```shell
cd bilibin
```

Create a Node project using `npm init`. 

> The `-y` flag tells the program to set some defaults about licensing and stuff like that.

```shell
npm init -y
```

This will have created a `package.json` file in your directory. This file is JSON metadata describing our project. It's not hugely interesting just yet.

Install the `cypress` module from the NPM module repository.

> The `--save-dev` flag tells `npm` to record the fact that we've installed this module inside the `package.json` file.

```shell
npm install --save-dev cypress
```
![install](https://user-images.githubusercontent.com/1855109/45778778-694fa400-bc51-11e8-9617-125f9dc905ab.png)

Installing Cypress can take a few minutes. Grab a coffee ☕️ and come back in a bit.

After Cypress has been installed, run it.

```shell
npx cypress open
```

![open](https://user-images.githubusercontent.com/1855109/45778784-710f4880-bc51-11e8-8a47-485fafac017f.png)

The first time we run Cypress like this it'll create some files and directories for us (scaffolding).

This scaffolding is all in the `./cypress` directory.

It'll contain a bunch of sample tests in the `./cypress/integration/` directory.

We can run those sample tests by clicking the `Run All` button in the top right of the Cypress app window.

If you encounter any errors at any of those steps, ping me and we'll work through them.

@jennifer-shehane I know that the docs repo ain't a support forum. Is there anything we might add to the docs to help folk who are coming to Cypress fresh? Thoughts?

**Comment by jennifer-shehane** [comment]
@richdouglasevans Perhaps we could have a line/note in the 'Installing' section that is like 

>Do not have node set up? See instructions on downloading node and Cypress from scratch

and/or 

>Having trouble installing on Windows? Read our step by step guide for installing Cypress on Windows

Then in the bottom, maybe under the 'Advanced' section, have a 'Troubleshooting' section with specific install instructions for these?

**Comment by tschernobyl** [comment]
Hi,
you're an angel! Following this I was able to launch Cypress from that sample directory.
![cypress-bilibin](https://user-images.githubusercontent.com/18416625/45800049-ec074c00-bcaf-11e8-80b2-589ddfea0b5d.PNG)

 Now launching from a pre-existing repo that was already `npm init`:ed. From there I am doing `npm install cypress --save-dev` again, getting version 1.4.2 this time.  (order of `cypress` and `--save-dev` apparently doesn't matter) and `npx cypress open`, and it works. 
Both `npx cypress open` and `node_modules\.bin\cypress` open work to launch the application.
![cypress-in-existing-repo](https://user-images.githubusercontent.com/18416625/45800452-3e953800-bcb1-11e8-85d1-71d6eef85fe0.PNG)

I get some disheartening security errors, but I guess those are a separate issue

**Comment by richdouglasevans** [comment]
Hurrah! Good stuff.

> I get some disheartening security errors, but I guess those are a separate issue

Yeah. The Cypress community on Gitter might be able to help: https://gitter.im/cypress-io/cypress

Have fun! 😄

**Comment by richdouglasevans** [comment]
> Linking to the bottom, maybe under the 'Advanced' section, have a 'Troubleshooting' section with specific install instructions for these?

Good suggestions Jennifer. I'll do that... soon. (Got a lot on at the mo' and I'm working my way through the architecture for this other ticket so uh, yeah, "soon" 😄 )

I reckon this ticket can be left open to track that&hellip; or I can open a focused one and this one can be closed. Your call, cheers!
