### ISSUE TITLE
Error docs related to parallelization should have link to parallelization docs

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress-documentation#974]
Every error related to parallelization should have a reference to parallelization docs

I don't think the `--parallel` should be linked, because that simply leads users to the command line reference, which gives very little info

![image](https://user-images.githubusercontent.com/14625260/45768007-abed8e00-bc09-11e8-81a3-8cbf5df8fd97.png)

**Comment by steakfrye** [comment]
I'm interested in implementing this, but I want to make sure I understand the issue. Let me know if this is correct and I'll start working on it.

The issue is on the [errors page](https://docs.cypress.io/guides/references/error-messages.html). Instead of linking [here](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-parallel) where the flag is not explained, it should point users to the [guide](https://docs.cypress.io/guides/guides/parallelization.html) to actually understand parallelization.
Is that right?

**Comment by Bkucera** [comment]
@steakfrye Thanks! I think we can take off the links from the `--parallel` and include blurbs on each error to visit parallelization guide
